/**
 * Applies pending migrations.  `npm run db:migrate`.
 *
 * Like `server/db/index.ts`, this file is aware that two engines exist —
 * unavoidably, because the migrator is driver-specific.  Nothing else is.
 *
 * Migrations are generated by `npm run db:generate` and never hand-edited
 * (CLAUDE.md §5.5).  The Postgres folder is generated from the Postgres schema
 * mirror; see `scripts/migrate-to-supabase.md` for the deployment-day runbook.
 */

import 'dotenv/config';
import { migrate as migrateSqlite } from 'drizzle-orm/better-sqlite3/migrator';
import { migrate as migratePg } from 'drizzle-orm/postgres-js/migrator';
import type { PostgresJsDatabase } from 'drizzle-orm/postgres-js';

import { DB_DIALECT, db } from './index';

const FOLDERS = {
  sqlite: 'server/db/migrations',
  postgres: 'server/db/migrations-pg',
} as const;

async function main(): Promise<void> {
  const migrationsFolder = FOLDERS[DB_DIALECT];
  console.log(`▸ applying migrations (dialect: ${DB_DIALECT}, from ${migrationsFolder})`);

  if (DB_DIALECT === 'postgres') {
    await migratePg(db as unknown as PostgresJsDatabase, { migrationsFolder });
  } else {
    migrateSqlite(db, { migrationsFolder });
  }

  console.log('✓ migrations applied');
}

main().catch((error: unknown) => {
  console.error('✗ migration failed:', error);
  process.exitCode = 1;
});
